# Site settings
title: Markus Reiter
email: me@reitermark.us
description: >
  I am Markus Reiter, currently studying computer science
  at the University of Innsbruck. My fields of interest
  include automation and graphic, type and web design.
baseurl: ''
url: https://markus.re
twitter_username: reitermarkus
github_username:  reitermarkus

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclusions
exclude: [
  '.gitignore',
  'ReadMe.md',
  'CNAME',
  'Gemfile',
  'Gemfile.lock',
]
