# Site Settings
title: Markus Reiter
email: me@reitermark.us
description: >
  I am Markus Reiter, currently studying computer science
  at the University of Innsbruck. My fields of interest
  include automation and graphic, type and web design.
baseurl: ''
url: https://reitermark.us
twitter_username: reitermarkus
github_username:  reitermarkus
timezone: Europe/Vienna

# Build Settings
markdown: kramdown

# Plugins
gems:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclusions
exclude: [
  '.gitignore',
  'ReadMe.md',
  'CNAME',
  'Gemfile',
  'Gemfile.lock',
]
